[package]
name = "nft_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
fuel-merkle = "0.35.1" 
primitive-types = { version = "0.12.1", features = ["serde"] }
rocksdb = { version = "0.21.0", optional = true }
rs_merkle = "1.4.1"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0.44"

[features]
default = []
native = ["rocksdb"]
